#!/bin/bash

set -e #exits script if there is an error

#update and install neccasary software
sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install macchanger -y    #changes MAC addresses
sudo apt-get install miniupnpc -y    #opens UPNP ports
sudo apt install wamerican    #creates dictionary for random /words in /usr/share/dict

#Set dynamic dns SECRETURL
SECRETURL=***YourSecretURLfromYourDNSproviderGoesHere***

#Location of each file being created
DISABLEIPV6="/etc/sysctl.conf"
ANONSCRIPT="/usr/local/bin/anonfile"
ANONSERVICE="/lib/systemd/system/anonscript.service"
KEEPALIVE="/usr/local/bin/keepalive"

#setup UPNP
upnpd ppp0 eth0
sudo route add -net 239.0.0.0 netmask 255.0.0.0 eth0
sudo route add -net 239.0.0.0 netmask 255.0.0.0 wlan0

#disable IPv6
#**************************************************************************************
/bin/cat <<EOM >$DISABLEIPV6
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
EOM
#**************************************************************************************

#write anonymizing script
#**************************************************************************************
/bin/cat <<EOM >$ANONSCRIPT
#!/bin/bash

#disable interfaces for modification
sudo ifconfig wlan0 down
sudo ifconfig eth0 down

#randomize MAC addresses
sudo macchanger -r wlan0
sudo macchanger -r eth0

#randomize hostname
RANDHOST=$(shuf -n1 /usr/share/dict/words) #pic random word from dictionary
HOSTNAME=$(echo $RANDHOST | tr -dc '[:alpha:]') #remove symbols
sudo hostname $HOSTNAME	#set hostname

sudo rm /etc/hostname #set hostname again, this time in the /etc/hostname file
echo $HOSTNAME >> /etc/hostname

sudo rm /etc/machine-id #remove and regenerate machine-id
sudo systemd-machine-id-setup

#re-enable interfaces
sudo ifconfig wlan0 up
sudo ifconfig eth0 up
EOM
#**************************************************************************************

#make anonymizing script executable
sudo chmod +x /usr/local/bin/anonscript

#create service unit to run anonscript at startup, before network connects
#**************************************************************************************
/bin/cat <<EOM >$ANONSERICE

[Unit]
Description=Run anonscript ASAP
Before=basic.target
After=local-fs.target sysinit.target
DefaultDependencies=no

[Service]
Type=oneshot
ExecStart=/usr/local/bin/anonscript

[Install]
WantedBy=basic.target
EOM
#**************************************************************************************

#enable newly created service
sudo systemctl daemon-reload
sudo systemctl enable anonscript.service

#listen on port 2222 instead of 22 for ssh
sudo sed -i '$ a\port 2222' /etc/ssh/sshd_config

#write keepalive script
#**************************************************************************************
/bin/cat <<EOM >$KEEPALIVE

sudo curl -ks $SECRETURL  > /dev/null
sudo upnpc -r 2222 tcp  > /dev/null
EOM
#**************************************************************************************

#use crontab to run the KEEPALIVE script every 5 minutes
sudo crontab -l | { cat; echo "*/5 * * * * $KEEPALIVE"; } | sudo crontab -
